// Package models contains the types for schema 'mydb'.
package models

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// DimensionDepartment represents a row from 'mydb.dimension_department'.
type DimensionDepartment struct {
	ID         int    `json:"id"`         // id
	Department string `json:"department"` // department

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the DimensionDepartment exists in the database.
func (dd *DimensionDepartment) Exists() bool {
	return dd._exists
}

// Deleted provides information if the DimensionDepartment has been deleted from the database.
func (dd *DimensionDepartment) Deleted() bool {
	return dd._deleted
}

// Insert inserts the DimensionDepartment to the database.
func (dd *DimensionDepartment) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if dd._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO mydb.dimension_department (` +
		`department` +
		`) VALUES (` +
		`?` +
		`)`

	// run query
	XOLog(sqlstr, dd.Department)
	res, err := db.Exec(sqlstr, dd.Department)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	dd.ID = int(id)
	dd._exists = true

	return nil
}

// Update updates the DimensionDepartment in the database.
func (dd *DimensionDepartment) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !dd._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if dd._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE mydb.dimension_department SET ` +
		`department = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, dd.Department, dd.ID)
	_, err = db.Exec(sqlstr, dd.Department, dd.ID)
	return err
}

// Save saves the DimensionDepartment to the database.
func (dd *DimensionDepartment) Save(db XODB) error {
	if dd.Exists() {
		return dd.Update(db)
	}

	return dd.Insert(db)
}

// Delete deletes the DimensionDepartment from the database.
func (dd *DimensionDepartment) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !dd._exists {
		return nil
	}

	// if deleted, bail
	if dd._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM mydb.dimension_department WHERE id = ?`

	// run query
	XOLog(sqlstr, dd.ID)
	_, err = db.Exec(sqlstr, dd.ID)
	if err != nil {
		return err
	}

	// set deleted
	dd._deleted = true

	return nil
}

// DimensionDepartmentByID retrieves a row from 'mydb.dimension_department' as a DimensionDepartment.
//
// Generated from index 'dimension_department_id_pkey'.
func DimensionDepartmentByID(db XODB, id int) (*DimensionDepartment, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, department ` +
		`FROM mydb.dimension_department ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	dd := DimensionDepartment{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&dd.ID, &dd.Department)
	if err != nil {
		return nil, err
	}

	return &dd, nil
}
