// Package models contains the types for schema 'mydb'.
package models

// GENERATED BY XO. DO NOT EDIT.

// DimensionDepartment represents a row from 'mydb.dimension_department'.
type DimensionDepartment struct {
	Department string `json:"department"` // department
}

// DimensionDepartmentByDepartment retrieves a row from 'mydb.dimension_department' as a DimensionDepartment.
//
// Generated from index 'dimension_department_department_pkey'.
func DimensionDepartmentByDepartment(db XODB, department string) (*DimensionDepartment, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`department ` +
		`FROM mydb.dimension_department ` +
		`WHERE department = ?`

	// run query
	XOLog(sqlstr, department)
	dd := DimensionDepartment{}

	err = db.QueryRow(sqlstr, department).Scan(&dd.Department)
	if err != nil {
		return nil, err
	}

	return &dd, nil
}
