// Package models contains the types for schema 'mydb'.
package models

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// DimensionGroup represents a row from 'mydb.dimension_group'.
type DimensionGroup struct {
	Group  string         `json:"group"`  // group
	Opaque sql.NullString `json:"opaque"` // opaque

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the DimensionGroup exists in the database.
func (dg *DimensionGroup) Exists() bool {
	return dg._exists
}

// Deleted provides information if the DimensionGroup has been deleted from the database.
func (dg *DimensionGroup) Deleted() bool {
	return dg._deleted
}

// Insert inserts the DimensionGroup to the database.
func (dg *DimensionGroup) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if dg._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO mydb.dimension_group (` +
		`opaque` +
		`) VALUES (` +
		`?` +
		`)`

	// run query
	XOLog(sqlstr, dg.Opaque)
	res, err := db.Exec(sqlstr, dg.Opaque)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	dg.Group = string(id)
	dg._exists = true

	return nil
}

// Update updates the DimensionGroup in the database.
func (dg *DimensionGroup) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !dg._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if dg._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE mydb.dimension_group SET ` +
		`opaque = ?` +
		` WHERE group = ?`

	// run query
	XOLog(sqlstr, dg.Opaque, dg.Group)
	_, err = db.Exec(sqlstr, dg.Opaque, dg.Group)
	return err
}

// Save saves the DimensionGroup to the database.
func (dg *DimensionGroup) Save(db XODB) error {
	if dg.Exists() {
		return dg.Update(db)
	}

	return dg.Insert(db)
}

// Delete deletes the DimensionGroup from the database.
func (dg *DimensionGroup) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !dg._exists {
		return nil
	}

	// if deleted, bail
	if dg._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM mydb.dimension_group WHERE group = ?`

	// run query
	XOLog(sqlstr, dg.Group)
	_, err = db.Exec(sqlstr, dg.Group)
	if err != nil {
		return err
	}

	// set deleted
	dg._deleted = true

	return nil
}

// DimensionGroupByGroup retrieves a row from 'mydb.dimension_group' as a DimensionGroup.
//
// Generated from index 'dimension_group_group_pkey'.
func DimensionGroupByGroup(db XODB, group string) (*DimensionGroup, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`group, opaque ` +
		`FROM mydb.dimension_group ` +
		`WHERE group = ?`

	// run query
	XOLog(sqlstr, group)
	dg := DimensionGroup{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, group).Scan(&dg.Group, &dg.Opaque)
	if err != nil {
		return nil, err
	}

	return &dg, nil
}
