// Package models contains the types for schema 'mydb'.
package models

// GENERATED BY XO. DO NOT EDIT.

// DimensionGroup represents a row from 'mydb.dimension_group'.
type DimensionGroup struct {
	Group string `json:"group"` // group
}

// DimensionGroupByGroup retrieves a row from 'mydb.dimension_group' as a DimensionGroup.
//
// Generated from index 'dimension_group_group_pkey'.
func DimensionGroupByGroup(db XODB, group string) (*DimensionGroup, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`group ` +
		`FROM mydb.dimension_group ` +
		`WHERE group = ?`

	// run query
	XOLog(sqlstr, group)
	dg := DimensionGroup{}

	err = db.QueryRow(sqlstr, group).Scan(&dg.Group)
	if err != nil {
		return nil, err
	}

	return &dg, nil
}
